{% set name = "tabulate" %}
{% set version = "0.9.0" %}
{% set sha256 = "0095b12bf5966de529c0feb1fa08671671b3368eec77d7ef7ab114be2c068b3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tabulate = tabulate:_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - tabulate
  commands:
    - tabulate --help
    - pip check

about:
  home: https://github.com/astanin/python-tabulate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pretty-print tabular data in Python, a library and a command-line utility.
  dev_url: https://github.com/astanin/python-tabulate

extra:
  recipe-maintainers:
    - jakirkham
    - synapticarbors
